# Collector specific configuration
countries_url: "https://api.wfp.org/gefs/1.1.0/geoless/collections/geographicalnames/items/countries?limit=1000"
token_url: "https://api.wfp.org/token"
base_url: "https://api.wfp.org/vam-data-bridges/2.0.0/"
currency_mappings:
  NIS: ILS
# Google sheet: https://docs.google.com/spreadsheets/d/1nXveHlfr4i4Fagxg9EOEYMpcTgK9CtWgKzQYiftIS6I/edit#gid=0
region_mapping_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRQUNinOiGZXU4w2M6Yd6Av0-Osead_c_prijShrcqGF0yYSoj9Nihxi2amIO-SAlE4XoQ9D3Bskq7I/pub?gid=0&single=true&output=csv"
# Google sheet: https://docs.google.com/spreadsheets/d/1YBT-ExQ3699ItBZCAj6nPFMPt5kh_8r-4xaXsm8azVU/edit#gid=926600343
source_overrides_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRIS7lB8DW70xF_PNoAsJZRLICs25abANZ2gvIX6ukwOhMz5kq3K1MutlL074HM3BfSsBptIwc4J4Cz/pub?gid=926600343&single=true&output=csv"

hxltags:
  countryiso3: "#country+code"
  date: "#date"
  admin1: "#adm1+name"
  admin2: "#adm2+name"
  market_id: "#loc+market+code"
  market: "#loc+market+name"
  latitude: "#geo+lat"
  longitude: "#geo+lon"
  category: "#item+type"
  commodity_id: "#item+code"
  commodity: "#item+name"
  unit: "#item+unit"
  priceflag: "#item+price+flag"
  pricetype: "#item+price+type"
  currency: "#currency"
  price: "#value"
  usdprice: "#value+usd"
  url: "#country+url"
  start_date: "#date+start"
  end_date: "#date+end"

country_headers:
  - date
  - admin1
  - admin2
  - market
  - latitude
  - longitude
  - category
  - commodity
  - unit
  - priceflag
  - pricetype
  - currency
  - price
  - usdprice

global_headers:
  - countryiso3
  - date
  - admin1
  - admin2
  - market
  - latitude
  - longitude
  - category
  - commodity
  - unit
  - priceflag
  - pricetype
  - currency
  - price
  - usdprice

qc_hxltags:
  date: "#date"
  code: "#meta+code"
  usdprice: "#value+usd"

currency_hxltags:
  code: "#currency+code"
  name: "#currency+name"
