# Collector specific configuration

prices_headers:
  - date
  - admin1
  - admin2
  - market
  - market_id
  - latitude
  - longitude
  - category
  - commodity
  - commodity_id
  - unit
  - priceflag
  - pricetype
  - currency
  - price
  - usdprice

markets_headers:
  - market_id
  - market
  - countryiso3
  - admin1
  - admin2
  - latitude
  - longitude
