# Collector specific configuration

commodities_headers:
  - commodity_id
  - category
  - commodity

currency_hxltags:
  code: "#currency+code"
  name: "#currency+name"

# This is where our definitions of admin levels differ so there is only admin 1
# data available in admin 2
unused_adm1:
  - "CIV"
  - "KEN"

# This is where our definitions of admin levels differ so there is only admin 2
# data available in admin 1
unused_adm2:
  - "DOM"
  - "RUS"
  - "UGA"

adm1_only:
  - "SLV"

hapi_dataset:
  name: "hdx-hapi-food-price"
  title: "HDX HAPI - Food Security, Nutrition & Poverty: Food Prices"
  tags:
    - "hxl"
    - "economics"
    - "markets"
    - "food security"
  dataset_source: "WFP - World Food Programme"
  license_id: "cc-by-igo"
  resources:
    - name: "Global Food Security, Nutrition & Poverty: Food Prices {}"
      description: "Food Prices & Market Monitor data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-prices-market-monitor) for more information"
      filename: "hdx_hapi_food_price_global_{}.csv"
      headers:
        - location_code
        - has_hrp
        - in_gho
        - provider_admin1_name
        - provider_admin2_name
        - admin1_code
        - admin1_name
        - admin2_code
        - admin2_name
        - admin_level
        - market_name
        - market_code
        - lat
        - lon
        - commodity_category
        - commodity_name
        - commodity_code
        - unit
        - price_flag
        - price_type
        - currency_code
        - price
        - usd_price
        - reference_period_start
        - reference_period_end
        - dataset_hdx_id
        - resource_hdx_id
        - warning
        - error
    - name: "Global Food Security, Nutrition & Poverty: Markets"
      description: "Markets data"
      filename: "hdx_hapi_market_global"
      headers:
        - location_code
        - has_hrp
        - in_gho
        - provider_admin1_name
        - provider_admin2_name
        - admin1_code
        - admin1_name
        - admin2_code
        - admin2_name
        - admin_level
        - market_name
        - market_code
        - lat
        - lon
        - dataset_hdx_id
        - resource_hdx_id
        - warning
        - error
    - name: "Global Food Security, Nutrition & Poverty: Commodities"
      description: "Commodities data"
      filename: "hdx_hapi_commodity_global"
      headers:
        - category
        - name
        - code
    - name: "Global Food Security, Nutrition & Poverty: Currencies"
      description: "Currencies data"
      filename: "hdx_hapi_currency_global"
      headers:
        - code
        - name
